# 参考：https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  # 默认排除规则下仍展示所有问题
  exclude-use-default: false
